Repository openremote/openremote, pull requests merged in 2025-03, with the labels that each got.

#1738 fix: add allowed roles annotation
  model/src/main/java/org/openremote/model/map/MapResource.java
Labels: Bug

#1737 Updated meta tags to not include 'demo'
  ui/app/console_loader/index.html
  ui/app/console_loader/src/index.ts
  ui/app/insights/index.html
  ui/app/manager/index.html
Labels: Enhancement

#1742 UI fix for maximumFractionDigits being forced to 20
  ui/component/or-mwc-components/src/or-mwc-input.ts
Labels: Bug

#1680 Rules grouping support, with tree dragging functionality
  ui/app/shared/locales/en/or.json
  ui/app/shared/locales/nl/or.json
  ui/component/or-rules/package.json
  ui/component/or-rules/src/index.ts
  ui/component/or-rules/src/or-rule-group-viewer.ts
  ui/component/or-rules/src/or-rule-list.ts
  ui/component/or-rules/src/or-rule-text-viewer.ts
  ui/component/or-rules/src/or-rule-tree.ts
  ui/component/or-rules/src/or-rule-validity.ts
  ui/component/or-rules/src/or-rule-viewer.ts
  ui/component/or-rules/src/style.ts
  ui/component/or-rules/tsconfig.json
  ui/component/or-tree-menu/.npmignore
  ui/component/or-tree-menu/README.md
  ui/component/or-tree-menu/build.gradle
  ui/component/or-tree-menu/package.json
  ui/component/or-tree-menu/src/index.ts
  ui/component/or-tree-menu/src/model.ts
  ui/component/or-tree-menu/src/or-tree-group.ts
  ui/component/or-tree-menu/src/or-tree-node.ts
  ui/component/or-tree-menu/src/util.ts
  ui/component/or-tree-menu/tsconfig.json
  ui/component/or-tree-menu/webpack.config.js
  yarn.lock
Labels: Feature

#1778 UI Fix for invisible children in or-asset-tree
  ui/component/or-asset-tree/src/index.ts
Labels: Bug
