Repository openremote/openremote, pull requests merged in 2025-05, with the labels that each got.

#1831 Added custom-elements.json generation
  project.gradle
  ui/.gitignore
  ui/build.gradle
  ui/component/custom-elements-manifest.config.js
  ui/component/or-app/build.gradle
  ui/component/or-app/package.json
  ui/component/or-asset-tree/build.gradle
  ui/component/or-asset-tree/package.json
  ui/component/or-asset-viewer/build.gradle
  ui/component/or-asset-viewer/package.json
  ui/component/or-attribute-card/build.gradle
  ui/component/or-attribute-card/package.json
  ui/component/or-attribute-history/build.gradle
  ui/component/or-attribute-history/package.json
  ui/component/or-attribute-input/build.gradle
  ui/component/or-attribute-input/package.json
  ui/component/or-attribute-picker/build.gradle
  ui/component/or-attribute-picker/package.json
  ui/component/or-bottom-navigation/package.json
  ui/component/or-chart/build.gradle
  ui/component/or-chart/package.json
  ui/component/or-chart/src/index.ts
  ui/component/or-components/build.gradle
  ui/component/or-components/package.json
  ui/component/or-dashboard-builder/build.gradle
  ui/component/or-dashboard-builder/package.json
  ui/component/or-data-viewer/build.gradle
  ui/component/or-data-viewer/package.json
  ui/component/or-gauge/build.gradle
  ui/component/or-gauge/package.json
  ui/component/or-icon/build.gradle
  ui/component/or-icon/package.json
  ui/component/or-json-forms/build.gradle
  ui/component/or-json-forms/package.json
  ui/component/or-log-viewer/build.gradle
  ui/component/or-log-viewer/package.json
  ui/component/or-map/build.gradle
  ui/component/or-map/package.json
  ui/component/or-mwc-components/build.gradle
  ui/component/or-mwc-components/package.json
  ui/component/or-rules/build.gradle
  ui/component/or-rules/package.json
  ui/component/or-smart-notify/build.gradle
  ui/component/or-smart-notify/package.json
  ui/component/or-survey-results/build.gradle
  ui/component/or-survey-results/package.json
  ui/component/or-survey/build.gradle
  ui/component/or-survey/package.json
  ui/component/or-thermostat/build.gradle
  ui/component/or-thermostat/package.json
  ui/component/or-timeline/build.gradle
  ui/component/or-timeline/package.json
  ui/component/or-translate/build.gradle
  ui/component/or-translate/package.json
  ui/component/or-tree-menu/build.gradle
  ui/component/or-tree-menu/package.json
  ui/util/package.json
  ui/util/webpack.util.js
  yarn.lock
Labels: Enhancement, Documentation

#1866 Update .gitignore
  .gitignore
Labels: Enhancement

#1842 Prevent or-mwc-menu from disrupting KPI attribute card layout (#1829)
  ui/component/or-attribute-card/src/index.ts
  ui/component/or-mwc-components/src/or-mwc-menu.ts
Labels: Bug

#1889 Upgrade anchore/scan-action to v6.2.0
  .github/workflows/ci_cd.yml
Labels: Enhancement

#1790 Feature/EBS Volume for storing/decoupling the IoT Data
  .ci_cd/aws/cloudformation-create-dashboard.yml
  .ci_cd/aws/cloudformation-create-ec2.yml
  .ci_cd/aws/cloudformation-create-efs.yml
  .ci_cd/aws/cloudformation-create-smtp-user.yml
  .ci_cd/aws/cloudformation-create-ssm-documents.yml
  .ci_cd/aws/cloudformation-create-vpc.yml
  .ci_cd/aws/cloudformation-healthcheck-alarm.yml
  .ci_cd/aws/provision_account.sh
  .ci_cd/aws/provision_host.sh
  .github/workflows/provision-host.yml
Labels: Feature

#1896 bugfix/volume size not applied on the volumes
  .ci_cd/aws/cloudformation-create-ec2.yml
  .ci_cd/aws/provision_host.sh
Labels: Bug
