Repository openremote/openremote, pull requests merged in 2025-01, with the labels that each got.

#1558 Added limit options on datapoint CSV export
  manager/src/main/java/org/openremote/manager/datapoint/AbstractDatapointService.java
  manager/src/main/java/org/openremote/manager/datapoint/AssetDatapointResourceImpl.java
  manager/src/main/java/org/openremote/manager/datapoint/AssetDatapointService.java
  model/src/main/java/org/openremote/model/datapoint/DatapointQueryTooLargeException.java
  profile/deploy.yml
  test/src/test/groovy/org/openremote/test/assets/AssetDatapointExportTest.groovy
  ui/app/manager/src/pages/page-export.ts
  ui/app/shared/locales/en/or.json
  ui/app/shared/locales/nl/or.json
Labels: Enhancement

#1576 bugfix: attribute in history card becomes unclickable after select.
  ui/component/or-asset-viewer/src/index.ts
Labels: Bug

#1566 disable autocomplete in user and account page
  ui/app/manager/src/pages/page-account.ts
  ui/app/manager/src/pages/page-users.ts
Labels: Enhancement

#1594 Fix duration reassignment for When-Then rules conditions
  ui/component/or-rules/src/json-viewer/or-rule-asset-query.ts
Labels: Bug

#1550 Updated username regex pattern based on Keycloak validation
  model/src/main/java/org/openremote/model/security/User.java
  test/src/test/groovy/org/openremote/test/users/UserResourceTest.groovy
  ui/app/manager/src/pages/page-account.ts
  ui/app/manager/src/pages/page-users.ts
Labels: Bug

#1602 Check for null response from HealthStatusProvider
  manager/src/main/java/org/openremote/manager/system/StatusResourceImpl.java
Labels: Bug

#1583 Added: Rules When-Then operator 'not updated for'
  manager/src/main/java/org/openremote/manager/rules/AssetQueryPredicate.java
  model/src/main/java/org/openremote/model/query/filter/AttributePredicate.java
  test/src/test/groovy/org/openremote/test/rules/residence/JsonRulesTest.groovy
  test/src/test/resources/org/openremote/test/rules/JsonNotUpdatedForRule.json
  ui/app/shared/locales/de/or.json
  ui/app/shared/locales/en/or.json
  ui/app/shared/locales/nl/or.json
  ui/component/or-rules/src/index.ts
  ui/component/or-rules/src/json-viewer/or-rule-asset-query.ts
  ui/component/or-rules/src/json-viewer/or-rule-json-viewer.ts
Labels: Feature

#1525 [Flow rules] Add historic value, sum, maximum, minimum, average, median, derivative, and integral blocks
  manager/src/main/java/org/openremote/manager/rules/FlowRulesBuilder.java
  manager/src/main/java/org/openremote/manager/rules/flow/FlowResourceImpl.java
  manager/src/main/java/org/openremote/manager/rules/flow/NodeExecutionRequestInfo.java
  manager/src/main/java/org/openremote/manager/rules/flow/NodeModel.java
  model/src/main/java/org/openremote/model/datapoint/query/AssetDatapointNearestQuery.java
  model/src/main/java/org/openremote/model/datapoint/query/AssetDatapointQuery.java
  model/src/main/java/org/openremote/model/rules/flow/Node.java
  model/src/main/java/org/openremote/model/rules/flow/NodeDataType.java
  model/src/main/java/org/openremote/model/rules/flow/NodeInternal.java
  model/src/main/java/org/openremote/model/rules/flow/PickerType.java
  test/src/test/groovy/org/openremote/test/rules/residence/FlowRulesTest.groovy
  test/src/test/resources/org/openremote/test/rules/HistoricAndMultiInputProcessorTest.flow
  ui/app/shared/locales/ar/or.json
  ui/app/shared/locales/cn/or.json
  ui/app/shared/locales/de/or.json
  ui/app/shared/locales/en/or.json
  ui/app/shared/locales/es/or.json
  ui/app/shared/locales/fr/or.json
  ui/app/shared/locales/it/or.json
  ui/app/shared/locales/nl/or.json
  ui/app/shared/locales/pt/or.json
  ui/app/shared/locales/ro/or.json
  ui/app/shared/locales/uk/or.json
  ui/component/or-rules/src/flow-viewer/components/flow-editor.ts
  ui/component/or-rules/src/flow-viewer/components/flow-node-socket.ts
  ui/component/or-rules/src/flow-viewer/components/flow-node.ts
  ui/component/or-rules/src/flow-viewer/components/internal-picker.ts
  ui/component/or-rules/src/flow-viewer/components/node-menu-item.ts
  ui/component/or-rules/src/flow-viewer/components/node-panel.ts
  ui/component/or-rules/src/flow-viewer/components/workspace-contextmenu-options.ts
  ui/component/or-rules/src/flow-viewer/node-structure/index.ts
  ui/component/or-rules/src/flow-viewer/node-structure/socket.type.matcher.ts
  ui/component/or-rules/src/flow-viewer/services/project.ts
  ui/component/or-rules/src/flow-viewer/styles/flow-node-style.ts
  ui/component/or-rules/src/flow-viewer/styles/picker-styles.ts
Labels: Feature

#1638 Hotfix for users page not functioning
  ui/app/manager/src/pages/page-account.ts
  ui/app/manager/src/pages/page-users.ts
Labels: Bug
