Repository openremote/openremote, pull requests merged in 2025-06, with the labels that each got.

#1847 Feature/Add global mapsettings override and fine-grain styling support
  manager/src/main/java/org/openremote/manager/map/MapService.java
  model/src/main/java/org/openremote/model/manager/MapConfig.java
  test/src/test/groovy/org/openremote/test/map/MapResourceTest.groovy
  ui/app/manager/src/components/configuration/or-conf-json.ts
  ui/app/manager/src/components/configuration/or-conf-map/or-conf-map-global.ts
  ui/app/manager/src/pages/page-configuration.ts
  ui/app/shared/locales/en/or.json
  ui/app/shared/locales/nl/or.json
  ui/component/or-map/src/mapbox-url-utils.ts
  ui/component/or-map/src/mapwidget.ts
Labels: Feature

#1922 UI enhancement: added icon to toggle password visibility
  ui/component/or-mwc-components/src/or-mwc-input.ts
Labels: Enhancement

#1894 Add Keycloak IdP APIs
  manager/src/main/java/org/openremote/manager/security/ManagerKeycloakIdentityProvider.java
  model/src/main/java/org/openremote/model/security/User.java
  test/src/test/groovy/org/openremote/test/security/IdentityProviderTest.groovy
Labels: Enhancement

#1915 MQTT agent subscription threading and renewal bug fix
  agent/src/main/java/org/openremote/agent/protocol/io/AbstractIOClientProtocol.java
  agent/src/main/java/org/openremote/agent/protocol/io/AbstractNettyIOClient.java
  agent/src/main/java/org/openremote/agent/protocol/mqtt/AbstractMQTT_IOClient.java
  agent/src/main/java/org/openremote/agent/protocol/mqtt/MQTTMessage.java
  agent/src/main/java/org/openremote/agent/protocol/mqtt/MQTTProtocol.java
  agent/src/main/java/org/openremote/agent/protocol/mqtt/MQTT_IOClient.java
  gradle.properties
  manager/src/main/java/org/openremote/manager/mqtt/DefaultMQTTHandler.java
  manager/src/main/java/org/openremote/manager/mqtt/MQTTBrokerService.java
  manager/src/main/java/org/openremote/manager/mqtt/UserAssetProvisioningMQTTHandler.java
  manager/src/main/resources/logging-dev.properties
  setup/src/integration/java/org/openremote/setup/integration/ManagerTestSetup.java
  test/src/test/groovy/org/openremote/test/assets/AssetPermissionsTest.groovy
  test/src/test/groovy/org/openremote/test/assets/AssetQueryTest.groovy
  test/src/test/groovy/org/openremote/test/assets/AssetUserLinkingTest.groovy
  test/src/test/groovy/org/openremote/test/mqtt/MqttBrokerTest.groovy
  test/src/test/groovy/org/openremote/test/protocol/mqtt/MQTTClientProtocolTest.groovy
  test/src/test/groovy/org/openremote/test/protocol/websocket/WebsocketClientTest.groovy
  test/src/test/groovy/org/openremote/test/provisioning/UserAndAssetProvisioningTest.groovy
Labels: Bug

#1957 Prevent parallel rule execution
  manager/src/main/java/org/openremote/manager/rules/RulesEngine.java
  test/src/test/groovy/org/openremote/test/rules/RulesEngineFiringTest.groovy
  test/src/test/resources/org/openremote/test/rules/ParallelEngineCheck.groovy
Labels: Bug
