Repository openremote/openremote, pull requests merged in 2025-04, with the labels that each got.

#1789 Update permissions needed for Roles and Realms page
  ui/app/manager/src/pages/page-realms.ts
  ui/app/manager/src/pages/page-roles.ts
  ui/app/manager/src/pages/page-users.ts
Labels: Bug

#1791 Improve responsiveness of add asset dialog
  ui/component/or-asset-tree/src/or-add-asset-dialog.ts
  ui/component/or-rules/src/json-viewer/or-rule-action-notification.ts
Labels: Bug

#1811 Bugfix/or-asset-viewer locked after saving with constraint violation
  ui/component/or-asset-viewer/src/index.ts
Labels: Bug

#1821 Fix path based proxying issues
  ui/app/manager/src/components/configuration/or-conf-realm/or-conf-realm-card.ts
  ui/app/manager/src/index.ts
  ui/app/manager/src/pages/page-configuration.ts
  ui/component/core/src/index.ts
  ui/component/or-app/src/index.ts
  ui/component/or-survey/src/index.ts
  ui/util/webpack.util.js
Labels: Bug

#1835 Add custom map upload and tile server URL configuration tests
  manager/src/main/java/org/openremote/manager/map/MapResourceImpl.java
  manager/src/main/java/org/openremote/manager/map/MapService.java
  model/src/main/java/org/openremote/model/map/MapResource.java
  test/src/test/groovy/org/openremote/test/map/MapResourceTest.groovy
Labels: Test

#1727 Simplified Dashboard permissions model
  manager/src/main/java/org/openremote/manager/dashboard/DashboardResourceImpl.java
  manager/src/main/java/org/openremote/manager/dashboard/DashboardStorageService.java
  manager/src/main/resources/org/openremote/manager/setup/database/V20250422_01__DashboardAccess.sql
  model/src/main/java/org/openremote/model/dashboard/Dashboard.java
  model/src/main/java/org/openremote/model/query/DashboardQuery.java
  setup/src/demo/resources/demo/dashboards/manufacturer/harvesting.json
  setup/src/demo/resources/demo/dashboards/smartcity/parking.json
  test/src/test/groovy/org/openremote/test/dashboard/DashboardTest.groovy
  ui/app/insights/src/components/dashboard-menu.ts
  ui/app/shared/locales/en/or.json
  ui/app/shared/locales/nl/or.json
  ui/app/shared/locales/ro/or.json
  ui/app/shared/locales/uk/or.json
  ui/component/or-dashboard-builder/src/index.ts
  ui/component/or-dashboard-builder/src/or-dashboard-boardsettings.ts
  ui/component/or-dashboard-builder/src/or-dashboard-preview.ts
  ui/component/or-dashboard-builder/src/or-dashboard-tree.ts
  ui/component/or-dashboard-builder/src/util/settings-panel.ts
Labels: Enhancement

#1832 Update AWS Marketplace listing
  .ci_cd/aws/cloudformation-aws-marketplace.yml
  .ci_cd/aws/img/or-aws-marketplace-architecture.png
Labels: Enhancement

#1838 bugfix/super admin can't open or delete alarms in other realms
  manager/src/main/java/org/openremote/manager/alarm/AlarmResourceImpl.java
  manager/src/main/java/org/openremote/manager/alarm/AlarmService.java
  manager/src/main/java/org/openremote/manager/rules/facade/AlarmFacade.java
  test/src/test/groovy/org/openremote/test/alarm/AlarmResourceTest.groovy
  test/src/test/groovy/org/openremote/test/rules/AlarmRuleTest.groovy
Labels: Bug

#1849 UI Fix: Flow Rules wiring not removed anymore during user changes
  ui/component/or-rules/src/flow-viewer/services/project.ts
Labels: Bug

#1850 UI Fix: Insights can now be opened without authentication again
  ui/app/insights/src/pages/page-view.ts
  ui/component/core/src/index.ts
Labels: Bug

#1845 Upgrade hibernate to latest release
  gradle.properties
  model/src/main/java/org/openremote/model/attribute/AttributeMap.java
  model/src/main/java/org/openremote/model/util/HibernateUniqueIdentifierGenerator.java
  model/src/main/java/org/openremote/model/util/HibernateUniqueIdentifierType.java
  test/src/test/groovy/org/openremote/test/console/ConsoleTest.groovy
Labels: Enhancement
